// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    if (cs.module !== 'Streams') {
      return;
    }
    return $(document).on('click', '.cs-streams-social-links > *', function() {
      var $this, id, link, params, parent;
      $this = $(this);
      parent = $this.parent();
      id = parent.data('id');
      link = $('base').attr('href') + 'Streams/' + id;
      params = 'location=no,width=500,height=400,resizable=no,status=no';
      if ($this.hasClass('vk')) {
        return window.open('https://vk.com/share.php?url=' + link, 'share_opir.org', params);
      } else if ($this.hasClass('fb')) {
        return window.open('https://www.facebook.com/sharer/sharer.php?src=sp&u=' + link, 'share_opir.org', params);
      } else if ($this.hasClass('tw')) {
        return window.open('https://twitter.com/intent/tweet?status=' + link, 'share_opir.org', params);
      }
    });
  });

}).call(this);
