// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var added_tags, found_tags, last, stream_filter;
    stream_filter = $('.cs-stream-filter');
    last = '';
    added_tags = $('.cs-stream-added-tags');
    found_tags = $('.cs-stream-found-tags');
    stream_filter.keyup(function() {
      var val;
      val = stream_filter.val();
      if (last === val) {
        return;
      }
      last = val;
      if (val.length > 2) {
        return $.ajax({
          url: 'api/Streams/tags',
          data: {
            title: val
          },
          type: 'get',
          success: function(tags) {
            var tag;
            return found_tags.html(((function() {
              var _results;
              _results = [];
              for (tag in tags) {
                tag = tags[tag];
                _results.push("<button data-id=\"" + tag.id + "\"><i class=\"uk-icon-plus\"></i> " + tag.title + "</button>");
              }
              return _results;
            })()).join());
          },
          error: function() {
            return found_tags.html('');
          }
        });
      }
    });
    added_tags.on('click', 'button', function() {
      $(this).remove();
      return map.add_streams_on_map();
    });
    return found_tags.on('click', 'button', function() {
      added_tags.append($(this).detach()[0].outerHTML.replace(/uk-icon-plus/, 'uk-icon-times'));
      map.add_streams_on_map();
      last = '';
      return stream_filter.val('');
    });
  });

}).call(this);
