// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    if (!cs.home.automaidan_coord) {
      return;
    }
    return ymaps.ready(function() {
      var check_event, check_event_id, clusterer, refresh_delay;
      refresh_delay = 5;
      clusterer = new ymaps.Clusterer();
      check_event_id = 0;
      (function() {
        var init;
        return init = setInterval((function() {
          var update_drivers;
          if (!window.map) {
            return;
          }
          clearInterval(init);
          map.geoObjects.add(clusterer);
          update_drivers = function() {
            $.ajax({
              url: 'api/Home/drivers',
              type: 'get',
              complete: function() {
                return setTimeout(update_drivers, refresh_delay * 1000);
              },
              success: function(drivers) {
                var driver, placemarks, _fn;
                placemarks = [];
                _fn = function(id) {
                  if (driver.busy) {
                    return;
                  }
                  return placemarks[placemarks.length - 1].events.add('click', function() {
                    return check_event(id);
                  });
                };
                for (driver in drivers) {
                  driver = drivers[driver];
                  driver.busy = parseInt(driver.busy);
                  placemarks.push(new ymaps.Placemark([driver.lat, driver.lng], {}, {
                    iconLayout: 'default#image',
                    iconImageHref: '/components/modules/Home/includes/img/driver.png',
                    iconImageSize: [40, 38],
                    iconImageOffset: [-16, -38],
                    iconImageClipRect: [[40 * driver.busy, 0], [40 * (driver.busy + 1), 38]]
                  }));
                  _fn(driver.id);
                }
                clusterer.removeAll();
                clusterer.add(placemarks);
              }
            });
          };
          update_drivers();
          return cs.home.delete_event = function(id) {
            if (!confirm('Точно видалити?')) {
              return;
            }
            $.ajax({
              url: "api/Home/events/" + id,
              type: 'delete',
              success: function() {
                update_drivers();
              }
            });
          };
        }), 100);
      })();
      $('#map').on('click', '.cs-home-check-assign', function() {
        check_event_id = $(this).data('id');
        return alert('Тепер оберіть вільного водія поблизу (синього кольору)');
      });
      return check_event = function(driver) {
        return $.ajax({
          url: "api/Home/events/" + check_event_id + "/check",
          data: {
            driver: driver
          },
          type: 'post',
          success: function() {
            map.balloon.close();
            check_event_id = 0;
            return alert('Водій отримав повідомлення про перевірку');
          }
        });
      };
    });
  });

}).call(this);
