// Generated by CoffeeScript 1.4.0
(function() {
  var initialized;

  initialized = false;

  window.init_disqus = function() {
    var dsq;
    dsq = document.createElement('script');
    dsq.type = 'text/javascript';
    dsq.async = true;
    dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
    return (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
  };

}).call(this);
