// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    if (cs.is_guest) {
      $('.cs-home-sign-in').click(function() {
        return $("<div>\n	<div class=\"uk-form\" style=\"width: 600px;margin-left: -300px;\">\n		<a class=\"uk-modal-close uk-close\"></a>\n		<p>\n			<input type=\"text\" id=\"login\" placeholder=\"" + cs.Language.login + "\" autofocus>\n		</p>\n		<p>\n			<input type=\"password\" id=\"password\" placeholder=\"" + cs.Language.password + "\">\n		</p>\n		<p class=\"cs-right\">\n			<button class=\"uk-button\" onclick=\"cs.sign_in($('#login').val(), $('#password').val());\">" + cs.Language.sign_in + "</button>\n		</p>\n	</div>\n</div>").appendTo('body').cs().modal('show').on('uk.modal.hide', function() {
          return $(this).remove();
        });
      });
      $(document).on('keyup', '#login, #password', function(event) {
        if (event.which === 13) {
          return $(this).parent().parent().find('button').click();
        }
      });
      if (!cs.getcookie('opir_reformat')) {
        cs.setcookie('opir_reformat', 1);
        return $.cs.simple_modal("<p>Оскільки нагальна потреба в координації сил самооборони відпала, сайт переорієнтовується згідно ситуації в Україні.</p>\n<p>Основні цілі, що ставить команда opir.org перед собою - фіксування та контроль порушень під час процесу волевиявлення громадян на найближчих виборах, а саме: вибори Призидента, Парламенту та Мера Києва.</p>\n<p>Opir.org стане інструментом спостерігачів від різних партій та громадських організацій. Процес буде проходити наступним чином: спостерігач зніматиме все що відбувається на власний телефон з за допомогою ustream або youtube і транслюватиме це на сайт. В разі фіксування порушення запис зберігатиметься на окремих серверах для подальшого аналізу. Порушення фіксуватиметься на карті та підсвічуватиметься червоним маркером. В разі потреби на місце виїжджатимуть групи кваліфікованих юристів та журналістів для надання допомоги спостерігачам.</p>\n<p>Скоро оновлений opir.org ви побачите на своїх комп`ютерах а також зожете завантажити в Android Play Market та iOS App Store.</p>");
      }
    } else {
      return $('.cs-home-sign-out').click(function() {
        return cs.sign_out();
      });
    }
  });

}).call(this);
