// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var filter_category, map_container, panel;
    map_container = $('#map');
    panel = $('.cs-home-settings-panel, .cs-home-settings-coordinator');
    if (!cs.home.automaidan && !cs.home.automaidan_coord && !cs.is_admin) {
      panel.find('[data-id]').each(function() {
        if ($.inArray($(this).data('id'), [1, 3, 6, 7, 8, 17, 21, 22]) !== -1) {
          return $(this).remove();
        }
      });
      panel.find('[data-group]:not([data-id])').each(function() {
        var prev;
        prev = $(this).prev();
        if (prev.is('[data-group]:not([data-id])')) {
          return prev.remove();
        }
      });
    }
    $('.cs-home-settings').click(function() {
      map_container.animate({
        right: (panel.css('display') !== 'none' ? 0 : 310) + 'px'
      }, 'fast', function() {
        return map.container.fitToViewport();
      });
      return $('.cs-home-settings-panel').toggle('fast');
    });
    filter_category = $('.cs-home-filter-category');
    return filter_category.find('[data-id]').click(function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('active')) {
        $this.removeClass('active');
      } else {
        $(this).parent().find('.active').removeClass('active').end().end().addClass('active');
      }
      return map.update_events(true);
    }).end().find('[data-group]').not('[data-id]').click(function() {
      var group;
      group = $(this).data('group');
      $(".cs-home-filter-category [data-id][data-group=" + group + "]").toggleClass('active');
      return map.update_events(true);
    });
  });

}).call(this);
