// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var filter_category, map_container, panel;
    map_container = $('#map');
    panel = $('.cs-home-settings-panel, .cs-home-settings-coordinator');
    if (!cs.home.automaidan && !cs.home.automaidan_coord && !cs.is_admin) {
      panel.find('[data-id]').each(function() {});
      panel.find('[data-group]:not([data-id])').each(function() {
        var prev;
        prev = $(this).prev();
        if (prev.is('[data-group]:not([data-id])')) {
          return prev.remove();
        }
      });
    }
    $('.cs-home-settings').click(function() {
      var shown;
      shown = panel.css('width') !== '0px';
      map_container.animate({
        right: (shown ? 0 : 310) + 'px'
      }, 'fast', function() {
        return map.container.fitToViewport();
      });
      if (shown) {
        panel.animate({
          width: '0'
        }, 'fast');
        return $('.cs-home-settings').animate({
          right: '0'
        }, 'fast').removeClass('uk-icon-chevron-right').addClass('uk-icon-chevron-left');
      } else {
        panel.animate({
          width: '310'
        }, 'fast');
        return $('.cs-home-settings').animate({
          right: '310'
        }, 'fast').removeClass('uk-icon-chevron-left').addClass('uk-icon-chevron-right');
      }
    });
    filter_category = $('.cs-home-filter-category');
    return filter_category.find('[data-id]').click(function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('active')) {
        $this.removeClass('active');
      } else {
        $(this).parent().find('.active').removeClass('active').end().end().addClass('active');
      }
      return map.update_events(true);
    }).end().find('[data-group]').not('[data-id]').click(function() {
      var group;
      group = $(this).data('group');
      $(".cs-home-filter-category [data-id][data-group=" + group + "]").toggleClass('active');
      return map.update_events(true);
    });
  });

}).call(this);
