// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var map_container, panel;
    map_container = $('#map');
    panel = $('.cs-home-settings-panel');
    $('.cs-home-settings').click(function() {
      map_container.animate({
        right: (panel.css('display') !== 'none' ? 0 : 310) + 'px'
      }, 'fast', function() {
        return map.container.fitToViewport();
      });
      return $('.cs-home-settings-panel').toggle('fast');
    });
    $('.cs-home-filter-category [data-id], .cs-home-filter-urgency [data-id]').click(function() {
      var $this;
      $this = $(this);
      if ($this.hasClass('active')) {
        $this.removeClass('active');
      } else {
        $(this).parent().find('.active').removeClass('active').end().end().addClass('active');
      }
      return map.update_events(true);
    });
    return $('.cs-home-filter-category [data-group]').not('[data-id]').click(function() {
      var group;
      group = $(this).data('group');
      $(".cs-home-filter-category [data-id][data-group=" + group + "]").toggleClass('active');
      return map.update_events(true);
    });
  });

}).call(this);
