// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var location_updating, modal, stream_code;
    if (!cs.home.reporter) {
      return;
    }
    modal = $("<div>\n	<div class=\"uk-form\" style=\"width: 600px;margin-left: -300px;\">\n		<a class=\"uk-modal-close uk-close\"></a>\n		<p>\n			<textarea class=\"cs-home-stream-code\" placeholder=\"Вставте код плеєру з трансляцією (youtube чи ustream) або посилання на сторінку з трансляцією в youtube\"></textarea>\n		</p>\n		<p>Дозвольте браузеру завжди отримувати доступ до вашого місцезнаходження, це необхідно для трансляції!</p>\n		<p class=\"cs-right\">\n			<button class=\"uk-button cs-home-stream-code-save\">Почати трансляцію</button>\n		</p>\n	</div>\n</div>").appendTo('body').cs().modal('show').on('uk.modal.hide', function() {
      return $(this).remove();
    });
    stream_code = $('.cs-home-stream-code');
    if (cs.home.reporter !== 1) {
      stream_code.val(cs.home.reporter);
    }
    $('.cs-home-stream-code-save').click(function() {
      $(this).html($(this).html() + ' <i class="uk-icon-spinner uk-icon-spin"></i>');
      if (navigator.geolocation) {
        return navigator.geolocation.getCurrentPosition(function(position) {
          return $.ajax({
            url: 'api/Home/stream',
            type: 'put',
            data: {
              stream_code: stream_code.val(),
              lat: position.coords.latitude,
              lng: position.coords.longitude
            },
            success: function() {
              map.panTo([position.coords.latitude, position.coords.longitude]);
              setTimeout(location_updating, 10 * 1000);
              modal.cs().modal('hide');
              return map.update_events();
            }
          });
        }, function() {
          return alert('Не вдалось отримати доступ до вашого місцеположення');
        }, {
          enableHighAccuracy: true,
          timeout: 2 * 60 * 1000
        });
      } else {
        return alert('Потрібен доступ до вашого місцеположення, інакше трансляція не працюватиме');
      }
    });
    location_updating = function() {
      return navigator.geolocation.getCurrentPosition(function(position) {
        return $.ajax({
          url: 'api/Home/stream_location',
          type: 'put',
          data: {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          },
          complete: function() {
            return setTimeout(location_updating, 10 * 1000);
          },
          success: function() {
            return map.update_events();
          }
        });
      }, function() {}, {
        enableHighAccuracy: true,
        timeout: 2 * 60 * 1000
      });
    };
  });

}).call(this);
