// Generated by CoffeeScript 1.4.0

/**
 * @package        Elections
 * @category       modules
 * @author         Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @copyright      Copyright (c) 2014, Nazar Mokrynskyi
 * @license        MIT License, see license.txt
*/


(function() {

  $(function() {
    var L, add_violation_sidebar, map_container, precinct_sidebar, precincts_search_results;
    if (cs.module !== 'Elections') {
      return;
    }
    map_container = $('#map');
    precincts_search_results = $('.cs-elections-precincts-search-results');
    precinct_sidebar = $('.cs-elections-precinct-sidebar');
    add_violation_sidebar = $('.cs-elections-add-violation-sidebar');
    L = cs.Language;
    precincts_search_results.on('click', '[data-id]', function() {
      var $this, address, id;
      $this = $(this);
      id = parseInt($this.data('id'));
      address = $this.children('p').html();
      return cs.elections.open_precinct(id, address);
    });
    window.cs.elections = window.cs.elections || {};
    window.cs.elections.open_precinct = function(id, address) {
      var is_open, precinct, streams_container, violations_container, _ref;
      _ref = JSON.parse(localStorage.getItem('precincts'));
      for (precinct in _ref) {
        precinct = _ref[precinct];
        if (precinct.id === id) {
          break;
        }
      }
      is_open = precinct_sidebar.data('open');
      precinct_sidebar.html("<i class=\"cs-elections-precinct-sidebar-close uk-icon-times\"></i>\n<h2>" + L.precint_number(precinct.number) + ("</h2>\n<p class=\"cs-elections-precinct-sidebar-address\">\n	<i class=\"uk-icon-location-arrow\"></i>\n	" + address + "\n</p>\n<h2>" + L.video_stream + "</h2>\n<div class=\"cs-elections-precinct-sidebar-streams\">\n	<i class=\"uk-icon-spinner uk-icon-spin\"></i>\n</div>\n<h2>\n	<button class=\"cs-elections-precinct-sidebar-add-violation uk-icon-plus\" data-id=\"" + precinct.id + "\"></button>\n	" + L.violations + "\n</h2>\n<section class=\"cs-elections-precinct-sidebar-violations\">\n	<i class=\"uk-icon-spinner uk-icon-spin\"></i>\n</section>")).animate({
        width: 320
      }, 'fast').data('open', 1);
      if (!is_open) {
        add_violation_sidebar.animate({
          left: '+=320'
        }, 'fast');
        map_container.animate({
          left: '+=320'
        }, 'fast');
      }
      streams_container = $('.cs-elections-precinct-sidebar-streams');
      $.ajax({
        url: "api/Precincts/" + id + "/streams",
        type: 'get',
        data: null,
        success: function(streams) {
          var content, stream, _i, _len;
          content = '';
          for (_i = 0, _len = streams.length; _i < _len; _i++) {
            stream = streams[_i];
            content += "<iframe src=\"" + stream.stream_url + "\" frameborder=\"0\" scrolling=\"no\"></iframe>";
          }
          if (content) {
            return streams_container.html(content);
          } else {
            return streams_container.html("<p class=\"uk-text-center\">" + L.empty + "</p>");
          }
        },
        error: function() {
          return streams_container.html("<p class=\"uk-text-center\">" + L.empty + "</p>");
        }
      });
      violations_container = $('.cs-elections-precinct-sidebar-violations');
      return $.ajax({
        url: "api/Precincts/" + id + "/violations",
        type: 'get',
        data: null,
        success: function(violations) {
          var content, images, text, video, violation, _i, _j, _len, _len1, _results;
          content = '';
          for (_i = 0, _len = violations.length; _i < _len; _i++) {
            violation = violations[_i];
            text = violation.text ? "<p>" + violation.text.substr(0, 200) + "</p>" : '';
            images = violation.images.length ? "<img src=\"" + violation.images[0] + "\" alt=\"\">" : '';
            video = violation.video ? "<iframe src=\"" + violation.video + "\" frameborder=\"0\" scrolling=\"no\"></iframe>" : '';
            content += "<article>\n	" + text + "\n	" + images + "\n	" + video + "\n	<div class=\"cs-elections-precinct-sidebar-read-more\" data-id=\"" + violation.id + "\">" + L.read_more + " »</div>\n</article>";
          }
          if (content) {
            violations_container.html(content);
            _results = [];
            for (_j = 0, _len1 = violations.length; _j < _len1; _j++) {
              violation = violations[_j];
              _results.push($(".cs-elections-precinct-sidebar-read-more[data-id=" + violation.id + "]").data('violation', violation));
            }
            return _results;
          } else {
            return violations_container.html("<p class=\"uk-text-center\">" + L.empty + "</p>");
          }
        },
        error: function() {
          return violations_container.html("<p class=\"uk-text-center\">" + L.empty + "</p>");
        }
      });
    };
    return precinct_sidebar.on('click', '.cs-elections-precinct-sidebar-close', function() {
      if (!precinct_sidebar.data('open')) {
        return;
      }
      $('.cs-elections-violation-read-more-sidebar-close').click();
      precinct_sidebar.animate({
        width: 0
      }, 'fast').data('open', 0);
      add_violation_sidebar.animate({
        left: '-=320'
      }, 'fast');
      return map_container.animate({
        left: '-=320'
      }, 'fast');
    });
  });

}).call(this);
